apiVersion: v1
kind: Service
metadata:
  labels:
    app: alert-svc
  name: alert-svc
spec:
  type: NodePort
  ports:
    - name: port
      port: 30056
      protocol: TCP
      targetPort: 30056
      nodePort: 30056
  selector:
    app: alert-dash
