{
 "title": "Detalles de Sensor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "select id as __value, nombre_sensor as __text from esq_dash_iot.sensores order by id;"
   },
   {
    "name": "tipo_medicion",
    "label": "Tipo Medición",
    "query": "select nombre as __value, INITCAP(nombre) as __text from esq_dash_iot.tipo_mediciones"
   },
   { "name": "api_url", "query": "http://24.199.81.227:30055" },
   { "name": "esq", "query": "esq_dash_iot" }
  ]
 },
 "panels": [
  {
   "title": "Nombre Sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select nombre_sensor, inactivo as \"Estado\", bateria, dev_eui, topic \r\nfrom $esq.sensores where id in ($sensor)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 29 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $esq.getestadoalertasensor('$sensor', '${__from:date}', '${__to:date}') as \"Estado Alerta\""
    }
   ]
  },
  {
   "title": "Batería",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 29 }
   ]
  },
  {
   "title": "Información General",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<table>\n  {{#each this}}\n  \n  {{#if (eq @key \"statusColor\")}}\n  {{else}}\n  <tr>\n    <th>{{@key}}</th>\n    <td>{{this}}</td>\n  </tr>\n  {{/if}}\n  {{/each}}\n</table>"
   },
   "targets": [
    {
     "rawSql": "select \r\n  dev_eui as \"DevEUI\", \r\n  -- b.nombre as \"Bodega\",\r\n  -- to_char(\r\n  --   (fecha_instalacion at time zone 'America/Guayaquil'), \r\n  --   'YYYY-MM-DD\" \"HH:MI') as \"Fecha Instalación\",\r\n  topic as \"Topic\", \r\n  g.nombre as \"Nombre Gateway\"\r\nfrom $esq.sensores s \r\n  inner join $esq.gateways g on g.id = s.id_gateway\r\n  -- inner join $esq.bodegas b on b.id = s.id_bodega\r\nwhere s.id in ($sensor) limit 1"
    }
   ]
  },
  {
   "title": "Configuración",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select id, nombre from $esq.areas order by orden"
    },
    {
     "rawSql": "select id_area, fecha_instalacion from $esq.sensores where id in ($sensor)"
    }
   ]
  },
  { "title": "Registrar Nueva Calibración", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 6, "x": 8, "y": 3 } },
  {
   "title": "Calibraciones",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "targets": [
    {
     "rawSql": "select fecha as \"Fecha\", entidad as \"Entidad\"\r\nfrom $esq.calibraciones\r\nwhere id_sensor in ($sensor) \r\norder by fecha desc, id desc"
    }
   ]
  },
  { "title": "Medición: $tipo_medicion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "tipo_medicion" },
  {
   "title": "Histórico $tipo_medicion",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select $__timeGroup(tiempo, $__interval), INITCAP($tipo_medicion), valor as \" \"\r\nfrom $esq.mediciones where $__timeFilter(tiempo) and id_sensor in ($sensor) and tipo_medicion in ($tipo_medicion)\r\norder by time"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ($tipo_medicion)"
    },
    {
     "rawSql": "select unidad from esq_dash_iot.tipo_mediciones where nombre in ($tipo_medicion)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n ( select valor from $esq.mediciones \r\n  where $__timeFilter(tiempo) \r\n    and id_sensor in ($sensor) \r\n    and tipo_medicion in ($tipo_medicion)\r\n  order by tiempo desc limit 1 ) as \"Actual ${tipo_medicion:text}\", \r\n  max(valor) as \"Maximo ${tipo_medicion:text}\",\r\n  min(valor) as \"Minimo ${tipo_medicion:text}\"\r\nfrom $esq.mediciones \r\nwhere $__timeFilter(tiempo) \r\n  and id_sensor in ($sensor) \r\n  and tipo_medicion in ($tipo_medicion)"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ($tipo_medicion)"
    },
    {
     "rawSql": "select unidad from esq_dash_iot.tipo_mediciones where nombre in ($tipo_medicion)"
    }
   ]
  },
  {
   "title": "Limites $tipo_medicion",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    min, max, advertencia, alarma\r\nFROM $esq.limites\r\nWHERE id_sensor IN ($sensor) AND tipo_medicion IN ($tipo_medicion) \r\nlimit 1"
    }
   ]
  }
 ]
}