{
 "title": "Parametros",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Crear Area", "type": "volkovlabs-form-panel", "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "Lista de areas",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * from esq_dash_iot.areas"
    }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Lista de Parametros",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * from esq_dash_iot.parametros"
    }
   ]
  },
  {
   "title": "Lista de Tipos de Mediciones",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * from esq_dash_iot.tipo_mediciones"
    }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } }
 ]
}