apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dash-iot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Dash-IoT Project

  sourceRepos:
    #- '*'
    - https://github.com/duditas-xd/dash-iot-manifest.git

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'