apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: postgres
spec:
  project: dash-iot

  source:
    repoURL: https://github.com/duditas-xd/dash-iot-manifest.git
    targetRevision: main
    path: ./k8s/postgresql
    # helm:
    #   valueFiles:
    #     - values-test.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dash-iot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  ignoreDifferences:
    - group: "*"
      kind: "*"