{
 "title": "Detalles de Area",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "area",
    "label": "Area",
    "query": "select id as __value, nombre as __text from esq_dash_iot.areas order by orden"
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "WITH sensor_data AS ( \n  select id as __value, nombre_sensor as __text from \n  $esq.sensores where id_area in ($area) \n  and case when '$estado_sensor' = 'todos' then true \n    else inactivo::int::text = '$estado_sensor' end\n  and case when '$estado_alerta' = 'todos' then true \n    else \n  ( select esq_dash_iot.getestadoalertasensor(id::text, '${__from:date}', '${__to:date}') )::text = '$estado_alerta' \nend ) select * from sensor_data \nunion all SELECT 0 , 'No Sensor' WHERE NOT exists (SELECT 1 FROM sensor_data);\n\n\n\n\n-- select id as __value, nombre_sensor as __text from $esq.sensores where id_area in ($area) order by sensores.id"
   },
   { "name": "esq", "query": "esq_dash_iot" },
   { "name": "estado_alerta", "query": "todos" },
   { "name": "estado_sensor", "query": "todos" }
  ]
 },
 "panels": [
  { "type": "text", "options": { "content": "<h1><b>${area:text}</b></h1>" } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Sensores\" from $esq.sensores \r\nwhere inactivo = false and id_area in ($area)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) as \"Sens. inactivos\" from $esq.sensores \r\nwhere inactivo = true and id_area in ($area)"
    }
   ]
  },
  { "title": "Filtrar", "type": "volkovlabs-form-panel", "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 } },
  { "title": "Sensor: $sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "sensor" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "options": {
    "content": "<!-- \n<div class=\"contenedor-link\" style=\"width:100%;height:100%;display:flex;\">\n<a style=\"place-content:center;\" class=\"my-link\" href=\"/d/ddxwcck13f280b/sensor?orgId=1&var-sensor=2\">\n  Ir al Dashboard\n</a>\n</div> -->\n\n<div class=\"css-fi8eaj\" style=\"width:100%;display:flex;align-items:center;padding-top:8px;\">\n  <a class=\"my-link\" href=\"/d/ddxwcck13f280b/sensor?orgId=1&var-sensor=${sensor}\">\n    <button class=\"css-td06pi-button\" type=\"button\" title=\"\" data-testid=\"data-testid panel button-submit\" aria-disabled=\"false\">\n      <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" width=\"16\" height=\"16\" class=\"css-74awvt-Icon\">\n        <path d=\"M18,10.82a1,1,0,0,0-1,1V19a1,1,0,0,1-1,1H5a1,1,0,0,1-1-1V8A1,1,0,0,1,5,7h7.18a1,1,0,0,0,0-2H5A3,3,0,0,0,2,8V19a3,3,0,0,0,3,3H16a3,3,0,0,0,3-3V11.82A1,1,0,0,0,18,10.82Zm3.92-8.2a1,1,0,0,0-.54-.54A1,1,0,0,0,21,2H15a1,1,0,0,0,0,2h3.59L8.29,14.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0L20,5.41V9a1,1,0,0,0,2,0V3A1,1,0,0,0,21.92,2.62Z\"></path>\n      </svg>\n      <span class=\"css-1riaxdn\">Ir</span>\n    </button>\n  </a>\n</div>\n"
   }
  },
  {
   "title": "Bateria",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bateria from $esq.sensores where id in ($sensor) "
    }
   ]
  },
  {
   "title": "Historico Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(tiempo, $__interval), INITCAP('temperatura'), valor as \" \"\r\nfrom $esq.mediciones where $__timeFilter(tiempo) and id_sensor in ($sensor ) and tipo_medicion in ('temperatura')\r\norder by time"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('temperatura')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  ( select valor from $esq.mediciones \r\n  where $__timeFilter(tiempo) \r\n    and id_sensor in ($sensor) \r\n    and tipo_medicion in ('temperatura')\r\n  order by tiempo desc\r\n  limit 1 ) as \"Actual\", \r\n  min(valor) as \"Minimo\", max(valor) as \"Maximo\"\r\nfrom $esq.mediciones \r\nwhere $__timeFilter(tiempo) \r\n  and id_sensor in ($sensor) \r\n  and tipo_medicion in ('temperatura')"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('temperatura')"
    }
   ]
  },
  {
   "title": "Historico Humedad",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(tiempo, $__interval), INITCAP('humedad'), valor as \" \"\r\nfrom $esq.mediciones where $__timeFilter(tiempo) and id_sensor in ($sensor ) and tipo_medicion in ('humedad')\r\norder by time"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('humedad')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  ( select valor from $esq.mediciones \r\n  where $__timeFilter(tiempo) \r\n    and id_sensor in ($sensor) \r\n    and tipo_medicion in ('humedad')\r\n  order by tiempo desc\r\n  limit 1 ) as \"Actual\", \r\nmin(valor) as \"Minimo\", max(valor) as \"Maximo\"\r\nfrom $esq.mediciones \r\nwhere $__timeFilter(tiempo) \r\n  and id_sensor in ($sensor) \r\n  and tipo_medicion in ('humedad')"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('humedad')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select inactivo as \"Estado\" from $esq.sensores where id in ($sensor)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $esq.getestadoalertasensor($sensor, '${__from:date}', '${__to:date}') as \"Estado Alerta\""
    }
   ]
  }
 ]
}