{
 "title": "Lista de Sensores",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "WITH sensor_data AS ( \n  select id as __value, nombre_sensor as __text from \n  esq_dash_iot.sensores where  \n  case \n    when '$area' = '-1' then true \n    when '$area' = '0' then id_area is null\n    else id_area = '$area'::int end\n  and case when '$inactividad' = 'todos' then true \n    else inactivo::int::text = '$estado_sensor' end\n  and case when '$inactividad' = 'todos' then true \n    else \n  ( select esq_dash_iot.getestadoalertasensor(id::text, '${__from:date}', '${__to:date}') )::text = '$estado_alerta' \nend\n  order by id ) select * from sensor_data \nunion all SELECT -1 , 'No Hay Sensor' WHERE NOT exists (SELECT 1 FROM sensor_data);"
   },
   { "name": "estado_alerta", "query": "todos" },
   { "name": "inactividad", "query": "todos" },
   { "name": "esq", "query": "esq_dash_iot" },
   { "name": "area", "query": "-1" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select a.id, \r\na.nombre as \"Area\",\r\n( select count(*) from $esq.sensores where id_area = a.id and inactivo = false ) as \"S. Activos\",\r\n( select count(*) from $esq.sensores where id_area = a.id and inactivo = true ) as \"S. Inactivos\",\r\n( select $esq.getNumeroSensoresAlertaArea(a.id::text, '0', '${__from:date}', '${__to:date}') ) as \"Sin Alerta\",\r\n( select $esq.getNumeroSensoresAlertaArea(a.id::text, '1', '${__from:date}', '${__to:date}') ) as \"Normal\", \r\n( select $esq.getNumeroSensoresAlertaArea(a.id::text, '2', '${__from:date}', '${__to:date}') ) as \"Advertencia\",\r\n( select $esq.getNumeroSensoresAlertaArea(a.id::text, '3', '${__from:date}', '${__to:date}') ) as \"Alarma\" \r\nfrom $esq.areas a\r\n  left join $esq.sensores s on s.id_area = a.id\r\ngroup by a.id\r\norder by a.orden"
    }
   ]
  },
  {
   "title": "Historial de Alertas",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "\n{{!-- Verificar si hay alertas --}}\n{{#if data.[0]}} \n\n{{#each data.[0]}}\n  <div class=\"item\">\n    <div class=\"icono-container\">\n      {{#if estado_alerta}}\n        <i class=\"fa fa-exclamation-triangle\" style=\"color:rgb(242, 73, 92);color:{{colorTipoAlerta tipo_alerta estado_alerta}};\"></i>\n      {{else}}\n        <i class=\"fa fa-check-square\" style=\"color:rgb(115, 191, 105)\"></i>\n      {{/if}}\n    </div>\n    <div class=\"contenido\">\n      <div class=\"titulo\">\n        <div class=\"titulo-texto\">\n          {{!-- <a href=\"d/ddxwcck13f280b/sensor?orgId=1&var-sensor={{id_sensor}}\"> --}}\n            {{#if nombre_bodega}}{{nombre_bodega}} - {{/if}}\n            {{nombre_sensor}}\n          {{!-- </a> --}}\n        </div>\n      </div>\n      <div class=\"texto\">\n        {{#if (esMedicion tipo_alerta)}}\n          <span style=\"color:{{colorTipoAlerta tipo_alerta estado_alerta}};\">\n            {{capitalize tipo_alerta}}\n          </span>\n          {{capitalize tipo_medicion}} a {{valor}} {{unidad}}\n        {{/if}}\n        {{#if (eq tipo_alerta \"bateria_baja\")}}\n          <span style=\"color:{{colorTipoAlerta tipo_alerta estado_alerta}};\">\n            Batería\n          </span>\n          a {{valor}}%\n        {{/if}}\n        {{#if (eq tipo_alerta \"inactividad\")}}\n          <span style=\"color:{{colorTipoAlerta tipo_alerta estado_alerta}};\">\n            Inactividad\n          </span>\n          {{#if estado_alerta}}\n            de {{valor}} minutos\n          {{/if}}\n        {{/if}}\n\n        {{#if estado_alerta}}{{else}} - Normalizada{{/if}}\n      </div>\n    </div>\n    <div class=\"fecha\">\n      <div>\n        {{date fecha \"hh:mm A\"}}\n      </div>\n      <div>\n        {{date fecha \"DD/MM/YYYY\"}}\n      </div>\n    </div>\n  </div>\n{{/each}}\n\n{{else}}\n<div style=\"font-size: 2rem;font-weight: 500;text-align: center;margin-top:20px;\">\n  No hay Alertas\n</div>\n{{/if}}\n\n\n\n"
   },
   "targets": [
    {
     "rawSql": "select * from esq_dash_iot.vmostraralertas\r\norder by fecha desc, id_registro desc\r\nlimit 50"
    },
    { "rawSql": "values ('')" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) as \"Sensores\" from esq_dash_iot.sensores \r\nwhere inactivo = false and id in ($sensor)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) as \"Sens. inactivos\" from esq_dash_iot.sensores \r\nwhere inactivo = true and id in ($sensor)"
    }
   ]
  },
  {
   "title": "Filtrar",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "select id, nombre \r\nfrom $esq.areas union all values (-1, 'Todos'), (0, 'Sin Area')\r\norder by id"
    }
   ]
  },
  { "title": "Sensor: $sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "sensor" },
  {
   "title": "Bateria",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select bateria from $esq.sensores where id in ($sensor) "
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": {
    "content": "<h2 title=\"Detalles\" class=\"css-4sw7w0\">Detalles</h2>\n<ul>\n   <li>\n      <b>Area:</b>\n      {{#if nombre_area}}\n         {{nombre_area}}\n      {{else}}\n         <i style=\"color:#ff9830;\" class=\"fa fa-exclamation-circle\"></i>\n         Sin Area\n      {{/if}}\n   </li>\n</ul>"
   },
   "targets": [
    {
     "rawSql": "select a.nombre as nombre_area from esq_dash_iot.sensores s left join esq_dash_iot.areas a on a.id = s.id_area \r\nwhere s.id in ($sensor) limit 1"
    }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 3, "w": 1, "x": 10, "y": 10 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(tiempo, $__interval), INITCAP('temperatura'), valor as \" \"\r\nfrom $esq.mediciones where $__timeFilter(tiempo) and id_sensor in ($sensor ) and tipo_medicion in ('temperatura')\r\norder by time"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('temperatura')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $__timeGroup(tiempo, $__interval), INITCAP('Humedad'), valor as \" \"\r\nfrom $esq.mediciones where $__timeFilter(tiempo) and id_sensor in ($sensor ) and tipo_medicion in ('humedad')\r\norder by time"
    },
    {
     "rawSql": "select min, max, advertencia, alarma from esq_dash_iot.limites l \r\nwhere l.id_sensor in ($sensor) and l.tipo_medicion in ('humedad')"
    }
   ]
  },
  { "type": "canvas", "gridPos": { "h": 3, "w": 1, "x": 19, "y": 10 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select $esq.getestadoalertasensor($sensor, '${__from:date}', '${__to:date}') as \"Estado Alerta\""
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select inactivo as \"Estado\" from $esq.sensores where id in ($sensor)"
    }
   ]
  }
 ]
}