apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  labels:
    volume: "postgres-data-pv"
spec:
  capacity:
    storage: 100Mi
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql14-v4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      volume: "postgres-data-pv"