apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-svc
  name: postgres-svc
spec:
  ports:
  - name: postgres-port
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30060
  selector:
    app: postgres
  type: NodePort

