name: Api-Dash Imagen Docker
on:
  push:
    paths: 
      - 'api/**'

jobs:
  Build_API_Image:
    name: Construir imagen de API
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      - name: Archivos de repositorio 
        uses: actions/checkout@v4

      - name: Credenciales de GitHub Container Register
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Construir y guardar imagen API-DASH
        uses: docker/build-push-action@v6
        with:
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/api_dash:${{ github.sha }}
            ghcr.io/${{ github.repository }}/api_dash:latest
          context: ./api

      - name: Trigger workflow de reposotorio manifest
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ vars.REPO_NAME_MANIFEST }}
          event-type: trigger-update-workflow
          client-payload: >
            {
              "manifest_path": "./k8s/api-dash/api-deployment.yaml",
              "image_tag": "ghcr.io/${{ github.repository }}/api_dash:${{ github.sha }}"
            }
