#Crear imagen personalizada de Grafana
FROM grafana/grafana-oss:11.2.0

#Directorio de trabajo en Grafana
WORKDIR /etc/grafana/provisioning

# Copiar archivos de Dashboar iniciales al contenedor
COPY . .