apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
spec:
  type: NodePort
  ports:
    - name: port
      port: 30055
      protocol: TCP
      targetPort: 30055
      nodePort: 30055
  selector:
    app: api-dash
